#!/usr/bin/env python3
"""Documentation Index Generator

Scans markdown documentation across a repository, extracts YAML frontmatter,
and deterministically renders DOCS-INDEX.md grouped by lifecycle and status.
"""

import argparse
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path


def parse_frontmatter(file_path: Path):
    try:
        content = file_path.read_text(encoding="utf-8")
    except Exception:
        return None

    if not content.startswith("---"):
        return None

    parts = content.split("---", 2)
    if len(parts) < 3:
        return None

    fm_raw = parts[1]
    meta = {}
    for line in fm_raw.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if ":" in line:
            k, v = line.split(":", 1)
            key = k.strip()
            val = v.split("#")[0].strip()
            # Strip quotes
            if (val.startswith('"') and val.endswith('"')) or (val.startswith("'") and val.endswith("'")):
                val = val[1:-1]
            if val.lower() == "null":
                val = None
            meta[key] = val
    return meta


def generate_index(repo_root: Path, output_file: Path) -> str:
    repo_root = repo_root.resolve()
    docs = []

    exclude_dirs = {".git", ".github", "node_modules", "_backups", "_quarantine"}

    for root, dirs, files in os.walk(repo_root):
        dirs[:] = [d for d in dirs if d not in exclude_dirs]
        for f in files:
            if f.endswith(".md") or f.endswith(".markdown"):
                p = Path(root) / f
                rel_path = p.relative_to(repo_root).as_posix()
                if rel_path in ["DOCS-INDEX.md", "README-WORKSPACE.md", "QUARANTINE-README.md"]:
                    continue
                fm = parse_frontmatter(p)
                if fm and "doc_id" in fm:
                    docs.append({
                        "path": rel_path,
                        "doc_id": fm.get("doc_id", "N/A"),
                        "title": fm.get("title", rel_path),
                        "lifecycle": fm.get("lifecycle", "durable"),
                        "status": fm.get("status", "active"),
                        "visibility": fm.get("visibility", "unknown"),
                        "owner": fm.get("owner", "Unassigned"),
                        "review_by": fm.get("review_by", "N/A"),
                        "expires_when": fm.get("expires_when", "-"),
                        "superseded_by": fm.get("superseded_by", "-"),
                        "archived_on": fm.get("archived_on", "-"),
                        "archive_reason": fm.get("archive_reason", "-")
                    })

    # Group docs
    durable_active = [d for d in docs if d["lifecycle"] == "durable" and d["status"] == "active"]
    transient_active = [d for d in docs if d["lifecycle"] == "transient" and d["status"] == "active"]
    superseded = [d for d in docs if d["status"] == "superseded"]
    archived = [d for d in docs if d["status"] == "archived"]

    lines = []
    lines.append("# Documentation Index\n")
    lines.append(f"> Auto-generated by `generate_docs_index.py`. Do not edit manually.\n")
    lines.append(f"- **Total Tracked Documents:** {len(docs)}")
    lines.append(f"- **Durable Active:** {len(durable_active)}")
    lines.append(f"- **Transient:** {len(transient_active)}")
    lines.append(f"- **Superseded:** {len(superseded)}")
    lines.append(f"- **Archived:** {len(archived)}\n")

    lines.append("## Durable Active Documents")
    lines.append("| Doc ID | Title | Path | Review By | Owner |")
    lines.append("|---|---|---|---|---|")
    for d in sorted(durable_active, key=lambda x: x["doc_id"]):
        lines.append(f"| `{d['doc_id']}` | {d['title']} | [{d['path']}]({d['path']}) | {d['review_by']} | {d['owner']} |")
    lines.append("")

    lines.append("## Transient Active Documents")
    lines.append("| Doc ID | Title | Path | Expires When | Review By | Owner |")
    lines.append("|---|---|---|---|---|---|")
    for d in sorted(transient_active, key=lambda x: x["doc_id"]):
        lines.append(f"| `{d['doc_id']}` | {d['title']} | [{d['path']}]({d['path']}) | {d['expires_when']} | {d['review_by']} | {d['owner']} |")
    lines.append("")

    lines.append("## Superseded Documents")
    lines.append("| Doc ID | Title | Path | Superseded By | Owner |")
    lines.append("|---|---|---|---|---|")
    for d in sorted(superseded, key=lambda x: x["doc_id"]):
        lines.append(f"| `{d['doc_id']}` | {d['title']} | [{d['path']}]({d['path']}) | `{d['superseded_by']}` | {d['owner']} |")
    lines.append("")

    lines.append("## Archived Documents")
    lines.append("| Doc ID | Title | Path | Archived On | Archive Reason |")
    lines.append("|---|---|---|---|---|")
    for d in sorted(archived, key=lambda x: x["doc_id"]):
        lines.append(f"| `{d['doc_id']}` | {d['title']} | [{d['path']}]({d['path']}) | {d['archived_on']} | {d['archive_reason']} |")
    lines.append("")

    output_content = "\n".join(lines)
    if output_file:
        output_file.write_text(output_content, encoding="utf-8")
        print(f"✅ Generated {output_file} ({len(docs)} documents indexed).")

    return output_content


def main():
    parser = argparse.ArgumentParser(description="Generate repository DOCS-INDEX.md")
    parser.add_argument("--repo", default=".", help="Target repository directory (default: current)")
    parser.add_argument("--out", default="DOCS-INDEX.md", help="Output file path (default: DOCS-INDEX.md)")

    args = parser.parse_args()
    repo_path = Path(args.repo)
    out_path = Path(args.out) if args.out != "-" else None

    content = generate_index(repo_path, repo_path / out_path if out_path else None)
    if not out_path:
        print(content)


if __name__ == "__main__":
    main()
